Contact form
zohra-neda/Portfolio pull request #3
Opened 2023-03-29 10:53 UTC by zohra-neda

In this project we :
 - Add contact form and footer sections
 - Add  style for both contact form and footer sections
 - Update README.md file

2023-03-29 11:05 UTC, bobb-Rob requested changes
Hi @zohra-neda, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that should include code commits from your pair programming partner. Please ensure that your partner makes contributions to this pull request.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-03-29 14:33 UTC, Strangeal requested changes
Hi @zohra-neda and @yashodhicy, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Alt Text](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)
## Highlights


## Required Changes ♻️
- [ ] Kindly, remove the space below the `input`  field. Be show to stick to the Figma design template. In the below screenshot, you can see I have used red ink to point to that exact space.
- [ ] Also consider adding an `outline: none` to the form input so that when a user clicks on an input to type in their info they don't see that orange `border` outline around the input field
Your design:
<img width="326" alt="Screenshot 2023-03-29 at 07 06 27" src="https://user-images.githubusercontent.com/107192076/228567104-3895c0bc-51ac-4a2e-b732-6ffe8d7215ee.png">

Figma: 
<img width="346" alt="Screenshot 2023-03-29 at 07 09 37" src="https://user-images.githubusercontent.com/107192076/228567453-394c81e2-02d3-4793-af1a-baa818e0a313.png">

- [ ] Please change the `color` of your icons to match the Figma design.
Your design:
<img width="322" alt="Screenshot 2023-03-29 at 07 28 26" src="https://user-images.githubusercontent.com/107192076/228571413-846df2c7-9a07-4e3a-bfe1-ef2c37b362fd.png">

Figma:
<img width="346" alt="Screenshot 2023-03-29 at 07 28 05" src="https://user-images.githubusercontent.com/107192076/228571516-94d946fd-5022-4858-a13e-e6856fa2481c.png">


_Check the comments under the review._



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-29 14:33 UTC, Strangeal commented on index.html
> +                <li><img src="./images/mobile-images/about/Container.png" alt="" srcset=""></li>
Please it would be better to change the way you added the horizontal line below each `form` `input`. Instead of using an `image` you can simply use the `<hr>` tag which will make your life much easier.  The `<hr>` tag in `HTML` stands for **horizontal rule** and is used to insert a horizontal rule or a thematic break in an HTML page. To learn more on how it works [click here](https://www.w3schools.com/tags/tag_hr.asp)

2023-03-29 14:33 UTC, Strangeal commented on index.html
> +                </li>
Kindly check if a user can submit a `form` by clicking this `button` because currently, it's not working. Also please add a `hover` , `active` effect. Kindly refer to the below screenshot for more details on adding this effect
<img width="638" alt="Screenshot 2023-03-29 at 06 58 31" src="https://user-images.githubusercontent.com/107192076/228562485-60c8872d-f66f-4632-a655-e27ef84e1599.png">

2023-03-29 14:33 UTC, Strangeal commented on index.html
> +                <li><img src="./images/mobile-images/about/Container.png" alt="" srcset=""></li>
Please refer back to the comment I made about using the `<hr>` tag and apply the same here

2023-03-29 14:33 UTC, Strangeal commented on index.html
> +                </li>
Please refer back to the comment I made about using the `<hr>` tag and apply the same here

2023-03-29 17:35 UTC, ABDULALI3468 requested changes
# Changes Required 👍 

Hi @zohra-neda , 

<img src="https://media1.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

Great work on making the changes requested by a previous reviewer 👏 
You've done really well implementing some of the requested changes, but there are still some which aren't been addressed yet.


## Highlights 
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.


 ## Required Changes ♻️

> **_Check the comments below to have a look at the required changes._**

## Optional suggestions

**[OPTIONAL]** There is a horizontal scroll bar on the page consider removing it as it decreases the user experience on your portfolio.


## Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification.

> * This is My **GitHub**: ![GitHub followers](https://img.shields.io/github/followers/ABDULALI3468?label=ABDULALI&style=social)
> * This is My **Linkedin**: [![Linkedin Badge](https://img.shields.io/badge/-ABDUL%20ALI-blue?style=flat-square&logo=Linkedin&logoColor=white&link=https://www.linkedin.com/in/abdul-ali-5400bb216/)](https://www.linkedin.com/in/abdul-ali-5400bb216/)&nbsp;
> * This is My **Twitter**: [![Twitter Badge](https://img.shields.io/badge/-@mrabdul_ali_-1ca0f1?style=flat-square&labelColor=1ca0f1&logo=twitter&logoColor=white&link=https://twitter.com/mrabdul_ali)](https://twitter.com/mrabdul_ali)&nbsp;

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-29 17:35 UTC, ABDULALI3468 commented on index.html
> +                </li>
**1-** As requested by the previous Code Reviewer, although there is a `hover` styling on the button there is no `active button` styling so please consider adding it to the button so that when a user presses the button it changes the styles of the button.

## Solution:--

You can use the following styling to do so but consider reviewing it after adding the styles.

```
#contact-form #form-btn button:hover {
    background-color: #E05304;
    color: #F4F1F0;
}
```

**2-** Moreover, on clicking the button the form is not submitted. Please consider reviewing this feature as it's the main goal of this milestone.

2023-03-29 17:53 UTC, zohra-neda commented
If one or two field of the form is empty user can not send the form, I just make the fields required, there we will have an error by the browser. Is not enough? 
Please any suggestion?

2023-03-30 05:38 UTC, LionRouge1 requested changes
Hi @zohra-neda, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Suggested changes
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-03-30 05:38 UTC, LionRouge1 commented on index.html
> +        <p id="contact-form-p">I'm always interested in hearing about new projects, so if you'd like to chat please get in touch.</p>
- [OPTIONAL] Kindly move this `<p>` element outside of the `form` tag for semantics reasons.

2023-03-30 05:38 UTC, LionRouge1 commented on index.html
> +                    <button type="submit">Get in touch</button>
- [ ] As mentioned by the previous reviewers, please add a `hover`, and `active` effect to the buttons. Kindly refer to the below screenshot for more details on adding this effect to stick to Figma's design as much as possible.

![](https://user-images.githubusercontent.com/107192076/228562485-60c8872d-f66f-4632-a655-e27ef84e1599.png)

2023-03-30 05:38 UTC, LionRouge1 commented on index.html
> +                </li>
- [ ] As mentioned by the previous reviewers, the form doesn't submit when clicking on the button "Get in touch" even though all fields have been filled out. And I think it's because you wrap the `input` tags within a `label` tag. Kindly remove the `label` tags, we actually don't need them :smile: that will make your code clean, and also submit the form when clicking on the button "Get in touch".

- [OPTIONAL] I will highly recommend you remove the `ul` and `li` tags from the `form` tag. You can add the class name `input-box` directly to the `input` tags for semantics reasons. You can read more about HTML form [here](https://www.w3schools.com/html/html_forms.asp)

**HIT:** Your form could look like this:
```sh
<form id="form" action="https://formspree.io/f/xyyangbj" method="post">
  <input id="name" class="input-box" type="text" name="name" placeholder="Full name" maxlength="30" required><br><hr><br>
  <input id="email" class="input-box" type="email" name="email" placeholder="Email address" required><br><hr><br>
  <textarea id="msg" class="input-box" name="msg" maxlength="500" placeholder="Write me something..." required></textarea><br>
  <button type="submit">Get in touch</button>
</form>
```

2023-03-30 05:38 UTC, LionRouge1 commented on index.html
> +            </ul>
- [OPTIONAL] Please uses a `ul` tag to group your media icons, and `li` tag per icon; each icon has a link (`a` tag). Apart from being semantically correct, the `a` tag will let you connect your social networks with the icons, using `href`.

2023-04-04 15:39 UTC, levy002 approved these changes
### Hello @zohra-neda 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

## Status: APPROVED :fire:  :fire: 

## Highlights
- No linter errors :heavy_check_mark: 
- Well-detailed README :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-04 15:41 UTC, merged

2023-04-08 10:32 UTC, shella12 reviewed
Hi @zohra-neda , 

#  Status: Invalidated :red_circle: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that 

- [ ] Is already merged into the master branch. Please create another pull request for submission

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-08 11:42 UTC, zohra-neda commented
@shella12 ,
This project is already approved, and I did not send the last pull request.
Is there any problem, please?

2023-04-08 11:57 UTC, omer-creator commented
Zohra,
This is me trying to submit our collaborative project. I will give an
update on slack

On Sat, Apr 8, 2023, 4:43 PM Zohra Neda ***@***.***> wrote:

> @shella12 <https://github.com/shella12> ,
> This project is already approved, and I did not send the last pull request.
> Is there any problem, please?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/zohra-neda/Portfolio/pull/3#issuecomment-1500873579>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3QEPBDUUVOD276YDLRUVHDXAFFMNANCNFSM6AAAAAAWLZOQCA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>